config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #   get 'orders/show'
  # end
  # namespace :admin do
  #   get 'customers/index'
  #   get 'customers/show'
  #   get 'customers/edit'
  # end
  # namespace :admin do
  #   get 'genres/index'
  #   get 'genres/edit'
  # end
  # namespace :admin do
  #   get 'items/index'
  #   get 'items/new'
  #   get 'items/show'
  #   get 'items/edit'
  # end
  # namespace :admin do
  #   get 'homes/top'
  # end
  # namespace :public do
  #   get 'addresses/index'
  #   get 'addresses/edit'
  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/edit'
  #   get 'customers/unsubscribe'
  # end
  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end
  # devise_for :customers
  # devise_for :admins

  # 顧客用
# URL /customers/sign_in ...


  # devise_for :customers
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }
# 管理者用
# URL /admin/sign_in ...



  devise_for :admin
# root to の後のコントローラをpublicに指定してある↓
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
# resourcesの前にgetの記述を移動した
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  get 'customers/withdraw' => 'public/customers#withdraw'
  get 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/thanks' => 'public/orders#thanks'

  get 'admin' => 'admin/homes#top'

scope module: :public do
  resources :items, only: [:index, :show]

# resourceとscopeで上手くいかなかった↓
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :create, :index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      patch 'order_details/:id', to: 'orders#update_order_detail', as: 'update_order_detail'
    end
  end
get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  # validates :is_active, inclusion: { in: is_actives.keys }
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre
  
  def with_tax_price
    (self.price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品登録に失敗しました。"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品情報の更新に失敗しました。"
      render :edit
    end

  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <h2 class="text-center my-5">商品編集</h2>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %> 件 のエラーが発生しました</h2>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: [:admin, @item], url: {controller: 'items', action: 'update' }, local: true, method: :patch, class: 'col-6 mx-auto' do |f| %>
    <div class="form-group row my-4">
      <%= f.label :image, '商品画像', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.file_field :image, accept: "image/*", class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :name, '商品名', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :introduction, '商品説明', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_area :introduction, class: 'form-control', style: "outline: thick double #c0c0c0", rows: 10 %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :genre_id, 'ジャンル', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :genre_id, options_for_select(Genre.all.collect { |genre| [genre.name, genre.id] }, selected: @item.genre_id), { prompt: 'ジャンルを選択してください' }, { class: 'form-control', style: "outline: thick double #c0c0c0" } %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :price, '税抜価格', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8 input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">￥</span>
        </div>
        <%= f.number_field :price, class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
  
    <div class="form-group row my-4">
      <%= f.label :is_active, '販売ステータス', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, true, checked: @item.is_active, class: 'custom-control-input', id: 'is_active-on-sale' %>
          <%= f.label :is_active, '販売中', class: 'custom-control-label font-weight-bolder text-success', for: 'is_active-on-sale' %>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, false, checked: !@item.is_active, class: 'custom-control-input', id: 'is_active-off-sale' %>
          <%= f.label :is_active, '販売停止中', class: 'custom-control-label font-weight-bolder text-secondary', for: 'is_active-off-sale' %>
        </div>
      </div>
    </div>
    <div class="form-group row my-4 text-center">
      <div class="col-sm-8 offset-sm-3">
        <%= f.submit '変更を保存', class: "btn btn-lg", style: "background-color: #00fa9a; color: #ffffe0;" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h2 class="text-center my-5">商品一覧</h2>
  <div class="text-right">
    <%= link_to '＋', new_admin_item_path, class: 'btn btn-light btn-lg my-3 shadow p-3 mb-5 bg-white rounded' %>
  </div>
  <div class="container">
    <table class="table table-bordered">
      <thead style="background-color: rgba(60, 42, 33, 0.5); color: #E5E5CB; white-space: nowrap;">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>販売ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= number_with_delimiter(item.price) %></td>
          <td><%= item.genre.name %></td>
          <td class="<%= item.is_active ? 'text-success' : 'text-secondary' %> font-weight-bolder">
            <%= item.is_active ? '販売中' : '販売停止中' %>
          </td>
        </tr>
      <% end %>
     </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h2 class="text-center my-5">商品新規登録</h2>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %> 件 のエラーが発生しました</h2>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: [:admin, @item], local: true, class: 'col-6 mx-auto' do |f| %>
    <div class="form-group row my-4">
      <%= f.label :image, '商品画像', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.file_field :image, accept: "image/*", class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :name, '商品名', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :introduction, '商品説明', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.text_area :introduction, class: 'form-control', style: "outline: thick double #c0c0c0", rows: 10 %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :genre_id, 'ジャンル', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <%= f.select :genre_id, options_for_select(Genre.all.collect { |genre| [genre.name, genre.id] }, selected: @item.genre_id), { prompt: 'ジャンルを選択してください' }, { class: 'form-control', style: "outline: thick double #c0c0c0" } %>
      </div>
    </div>
    <div class="form-group row my-4">
      <%= f.label :price, '税抜価格', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8 input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">￥</span>
        </div>
        <%= f.number_field :price, class: 'form-control', style: "outline: thick double #c0c0c0" %>
      </div>
    </div>
  
    <div class="form-group row my-4">
      <%= f.label :is_active, '販売ステータス', class: 'col-sm-4 col-form-label' %>
      <div class="col-sm-8">
        <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, true, checked: @item.is_active, class: 'custom-control-input', id: 'is_active-on-sale' %>
          <%= f.label :is_active, '販売中', class: 'custom-control-label font-weight-bolder text-success', for: 'is_active-on-sale' %>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <%= f.radio_button :is_active, false, checked: !@item.is_active, class: 'custom-control-input', id: 'is_active-off-sale' %>
          <%= f.label :is_active, '販売停止中', class: 'custom-control-label font-weight-bolder text-secondary', for: 'is_active-off-sale' %>
        </div>
      </div>
    </div>
    <div class="form-group row text-center my-4">
      <div class="col-sm-8 offset-sm-3">
        <%= f.submit '新規登録', class: "btn btn-lg", style: "background-color: #00fa9a; color: #ffffe0;" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2 class="text-center my-5">商品詳細</h2>
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div>
        <%= image_tag url_for(@item.image), class: 'img-fluid', style: 'width: 80%;' %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="container">
        <table>
          <tr style="height: 80px;">
            <th style="width: 20%">商品名</th>
            <td><%= @item.name %></td>
          </tr>
          <tr style="height: 80px;">
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>
          <tr style="height: 80px;">
            <th>ジャンル</th>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr style="height: 80px;">
            <th>税込価格</br>(税抜価格)</th>
            <td><%= number_with_delimiter((@item.price * 1.1).round) %> ( <%= number_with_delimiter(@item.price) %> ) 円</td>
          </tr>
          <tr style="height: 80px;">
            <th>販売ステータス</th>
            <td class="<%= @item.is_active ? 'text-success' : 'text-secondary' %> font-weight-bolder">
              <%= @item.is_active ? '販売中' : '販売停止中' %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="text-center my-4">
      <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-lg", style: "background-color: #00fa9a; color: #ffffe0;" %>
    </div>
  </div>
</div>