config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #   get 'orders/show'
  # end
  # namespace :admin do
  #   get 'customers/index'
  #   get 'customers/show'
  #   get 'customers/edit'
  # end
  # namespace :admin do
  #   get 'genres/index'
  #   get 'genres/edit'
  # end
  # namespace :admin do
  #   get 'items/index'
  #   get 'items/new'
  #   get 'items/show'
  #   get 'items/edit'
  # end
  # namespace :admin do
  #   get 'homes/top'
  # end
  # namespace :public do
  #   get 'addresses/index'
  #   get 'addresses/edit'
  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/edit'
  #   get 'customers/unsubscribe'
  # end
  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end
  # devise_for :customers
  # devise_for :admins

  # 顧客用
# URL /customers/sign_in ...


  # devise_for :customers
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }
# 管理者用
# URL /admin/sign_in ...



  devise_for :admin
# root to の後のコントローラをpublicに指定してある↓
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
# resourcesの前にgetの記述を移動した
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  get 'customers/withdraw' => 'public/customers#withdraw'
  get 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/thanks' => 'public/orders#thanks'

  get 'admin' => 'admin/homes#top'

scope module: :public do
  resources :items, only: [:index, :show]

# resourceとscopeで上手くいかなかった↓
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :create, :index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      patch 'order_details/:id', to: 'orders#update_order_detail', as: 'update_order_detail'
    end
  end
get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :email
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :postal_code
    validates :telephone_number
    validates :address
  end
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def is_unactive_for_authentication?
    super && (is_active == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(15)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(params[:id]), notice: "編集内容を保存しました"
    else
      render 'edit'
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address,:telephone_number, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container px-2 px-sm-0'>
  <div class='row ml-5 pl-5 mt-3'>
    <h1 style="background-color: #dcdcdc; font-size: 24px;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
  </div>
  <% if @customer.errors.any? %>
    <%= @customer.errors.count %>件のエラーが発生しました
    <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @customer, url:  admin_customer_path(@customer.id) do |f| %>
    <table class='table table-sm mt-3 mb-5 table-borderless'>
      <tbody>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control form-control-sm" %></td>
          <td><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control form-control-sm" %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "form-control form-control-sm" %></td>
          <td><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: "form-control form-control-sm" %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "form-control form-control-sm" %></td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan="2"><%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control form-control-sm" %></td>
          <td></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: "form-control form-control-sm" %></td>
          <td></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control form-control-sm" %></td>
          <td></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td><%= f.radio_button :is_active, "true" %> 有効 <%= f.radio_button :is_active, "false" %> 退会</td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "変更内容保存",class: 'btn btn-lg btn-success btn-block' %></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <h2 class="text-center my-5">会員一覧</h2>
  <table class='table' style="width: 100%">
    <thead style="background-color: rgba(60, 42, 33, 0.5); color: #E5E5CB; white-space: nowrap;">
      <tr class="table-active">
        <td>会員ID</td>
        <td>氏名</td>
        <td>メールアドレス</td>
        <td>ステータス</td>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td style="width: 10%"><%= customer.id %></td>
        <td style="width: 15%"><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer.id) %></td>
        <td style="width: 25%"><%= customer.email %></td>
        <% if customer.is_active == true %>
          <td style="width: 35%" class="text-success">有効</td>
        <% else %>
          <td style="width: 35%" class="text-secondary">退会</td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container px-2 px-sm-0'>
  <div class='row ml-5 pl-5 mt-3'>
    <h1 style="background-color: #dcdcdc; font-size: 24px;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>
  </div>
  <table class='table mt-5 table-borderless'>
    <tr>
      <td style="width: 15%">会員ID</td>
      <td><%= @customer.id %></td>
      <td></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      <td></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      <td></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
      <td></td>
    </tr>
    <tr>
      <td>住所</td>
      <td colspan="2"><%= @customer.address %></td>
      <td></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
      <td></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
      <td></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <% if @customer.is_active == true %>
        <td style="width: 35%" class="text-success">有効</td>
      <% else %>
        <td style="width: 35%" class="text-secondary">退会</td>
      <% end %>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-sm btn-success" %></td>
      <td><%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-sm btn-primary" %></td>
    </tr>
  </table>
</div>