config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #   get 'orders/show'
  # end
  # namespace :admin do
  #   get 'customers/index'
  #   get 'customers/show'
  #   get 'customers/edit'
  # end
  # namespace :admin do
  #   get 'genres/index'
  #   get 'genres/edit'
  # end
  # namespace :admin do
  #   get 'items/index'
  #   get 'items/new'
  #   get 'items/show'
  #   get 'items/edit'
  # end
  # namespace :admin do
  #   get 'homes/top'
  # end
  # namespace :public do
  #   get 'addresses/index'
  #   get 'addresses/edit'
  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/edit'
  #   get 'customers/unsubscribe'
  # end
  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end
  # devise_for :customers
  # devise_for :admins

  # 顧客用
# URL /customers/sign_in ...


  # devise_for :customers
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }
# 管理者用
# URL /admin/sign_in ...



  devise_for :admin
# root to の後のコントローラをpublicに指定してある↓
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
# resourcesの前にgetの記述を移動した
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  get 'customers/withdraw' => 'public/customers#withdraw'
  get 'cart_items/destroy_all' => 'public/cart_items#destroy_all'
  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/thanks' => 'public/orders#thanks'

  get 'admin' => 'admin/homes#top'

scope module: :public do
  resources :items, only: [:index, :show]

# resourceとscopeで上手くいかなかった↓
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :create, :index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      patch 'order_details/:id', to: 'orders#update_order_detail', as: 'update_order_detail'
    end
  end
get '/genre/search' => 'searches#genre_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  admin = Admin.new(email: 'naganocake@gmail.com', password: '123abc')
  admin.save
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def quantity
    read_attribute(:quantity) || 0
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :email
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :postal_code
    validates :telephone_number
    validates :address
  end
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def is_unactive_for_authentication?
    super && (is_active == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  # validates :is_active, inclusion: { in: is_actives.keys }
  
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre
  
  def with_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer


  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :name, presence: true, length: { maximum: 30 }

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  after_update :update_order_status

  private

  def update_order_status
    order.update(status: "making") if manufacturing?
    if order.order_details.all? { |detail| detail.finish? }
      order.update(status: "preparing_ship")
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品登録に失敗しました。"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "商品情報の更新に失敗しました。"
      render :edit
    end

  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :telephone_number, :address])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color: #f08080;">
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto text-light'>
        <p>&copy;　2024　Suzuki,　Wang,　Masuda,　Infratop.inc.</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #f08080;">
    <div class="container">
      <a class="navbar-brand" href="/"><span><%= image_tag "NaganoCake_logo2.png", size: "100x100" %></span></a>
      <% if customer_signed_in? %>
        <p class="mx-5 text-light">ようこそ、 <%= current_customer.last_name %> さん！</p>
      <% elsif admin_signed_in? %>
        <p class="mx-5 text-danger font-weight-bold h3" style="text-shadow: 1px 2px 3px #203744;">管理者として<br>ログイン中 <i class="fa-solid fa-triangle-exclamation text-warning"></i></p>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="d-flex flex-column w-100">
          <ul class="navbar-nav my-2 ml-auto flex-row">
            
          <% if admin_signed_in? %>
            <li class="nav-item ml-3">
              <%= link_to admin_items_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-users-gear"></i> 会員一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-kitchen-set"></i> 注文履歴一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-tags"></i> ジャンル一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
            
          <% elsif customer_signed_in? %>
            <li class="nav-item ml-3">
              <%= link_to customers_my_page_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-user-large"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to cart_items_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-cart-shopping"></i> カート
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
            
          <% else %>
            <li class="nav-item ml-3">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-house-chimney"></i> About
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                <i class="mr-1 fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
          <% end %>
          
          </ul>
          <form class="form-inline my-2 mt-lg-0 ml-auto">
            <input class="form-control mr-sm-2" type="search" placeholder="商品検索" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
        </div>
      </div>
    </div>
  </nav>
</header>



<!--<header>-->
<!--  <div class="search-container">-->
<!--  <input type="text" placeholder="Search">-->
<!--  <span class="search-icon">&#128269;</span>-->
<!--　</div>-->

<!--  <%= link_to image_tag("NaganoCake.png", size: "100x100"), root_path %>-->
<!--  <% if admin_signed_in? %>-->
<!--    <%= link_to "商品一覧", admin_items_path %>-->
<!--    <%= link_to "会員一覧", admin_customers_path %>-->
<!--    <%= link_to "注文履歴一覧", admin_path %>-->
<!--    <%= link_to "ジャンル一覧", admin_genres_path %>-->
<!--    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>-->
<!--  <% elsif customer_signed_in? %>-->
<!--    <%= link_to "マイページ", customers_my_page_path %>-->
<!--    <%= link_to "商品一覧", items_path %>-->
<!--    <%= link_to "カート", cart_items_path %>-->
<!--    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>-->
<!--    ようこそ <%= current_customer.last_name %> さん-->
<!--  <% else %>-->
<!--    <%= link_to "About", about_path %>-->
<!--    <%= link_to "商品一覧", items_path %>-->
<!--    <%= link_to "新規登録", new_customer_registration_path %>-->
<!--    <%= link_to "ログイン", new_customer_session_path %>-->
<!--  <% end %>-->
<!--</header>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a7eeb2be5e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100" style="background-color: #ffffe0;">
    <%= render 'layouts/header' %>
    <main class="mb-auto background">
      <div class="container" style="position: relative;">
        <% if notice %>
          <p class="m-5 alert alert-primary alert-dismissible mx-auto text-center" style="box-shadow: 0px 5px 12px #cad4e2, -6px -6px 12px #fff">
            <strong><%= notice %></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </p>
        <% end %>
        <% if alert %>
          <p class="m-5 alert alert-danger alert-dismissible text-center" style="box-shadow: 0px 5px 12px #cad4e2, -6px -6px 12px #fff">
            <strong><%= alert %></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </p>
        <% end %>
      <%= yield %>
      <p style="height: 100px;"></p>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>